######################################################################
#  Project
######################################################################

BINARY		= helloBlink
SRCFILES	= helloBlink.c

all: elf bin

include ../Makefile.incl

# End
